# Generated by Django 2.0.4 on 2018-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='name',
        ),
    ]
